#!/bin/bash
# needs to be made executable "chmod -x radio" then to execute "./radio"
# or
# "sudo cp radio /usr/local/bin/radio" then to execure "radio"


x[0]="http://13873.live.streamtheworld.com:3690/FM702_SC"
x[1]="http://13303.live.streamtheworld.com:3690/CAPE_TALK_SC"
x[2]="http://www.listenlive.eu/bbcradio1.m3u"
x[3]="http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/http-icy-mp3-a/vpid/bbc_radio_berkshire/format/pls.pls"
x[4]="http://www.listenlive.eu/bbcradio4.m3u"
x[5]="http://www.listenlive.eu/bbcradio4extra.m3u"
x[6]="http://wsdownload.bbc.co.uk/worldservice/meta/live/shoutcast/mp3/eieuk.pls"
xname[0]="radio 702"
xname[1]="cape talk"
xname[2]="bbc one"
xname[3]="bbc radio berkshire"
xname[4]="bbc radio 4"
xname[5]="bbc radio 4 extra"
xname[6]="bbc world service"
if [ $# -eq 0 ]
	then
		echo "usage: ./radio 1"
		for ((i=0; i<${#x[@]}; i++))
			do
				echo $i for ${xname[$i]} 
			done
		exit 1
fi
if [ ${1} -eq 1 ] || [ ${1} -eq 0 ] 
	then
		echo "no playlist"
		mplayer -quiet ${x[${1}]}
	else
		echo "playlist"
		mplayer -quiet -playlist ${x[${1}]}
fi


